# Your personal GitHub token
# Generate at: https://github.com/settings/tokens
github_token: <your-personal-github-token>

# Guest OS timezone
timezone: Europe/Budapest

# Check updates on every 'vagrant up'?
box_check_update: false

# Virtual machine name
machine_name: ticketing-system-template.test

# Virtual machine CPU cores number
cpus: 1

# Virtual machine RAM
memory: 1024

network: 'private_network'

# Virtual machine IP
ip: 192.168.83.123

# Root folder name (should be the git project name)
root_folder: ticketing-system-template

# PostgreSQL configs
db_user: ticket_system
db_user_password: asd123
db_name: ticket_system
postgres_version: 11

# Apache domains
domains:
  frontend: ticketing-system.test
  backend: ticketing-system-backend.test
